/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    C0_CruiseDetailsView: typeof import('./src/components/User/CruiseInformation/C0_CruiseDetailsView.vue')['default']
    C1_BreadcrumbDetail: typeof import('./src/components/User/CruiseInformation/C1_BreadcrumbDetail.vue')['default']
    C2_YachtTitle: typeof import('./src/components/User/CruiseInformation/C2_YachtTitle.vue')['default']
    C3_Highlight: typeof import('./src/components/User/CruiseInformation/C3_Highlight.vue')['default']
    C4_RomCruise: typeof import('./src/components/User/CruiseInformation/C4_RomCruise.vue')['default']
    C5_Introduce: typeof import('./src/components/User/CruiseInformation/C5_Introduce.vue')['default']
    C6_Rules: typeof import('./src/components/User/CruiseInformation/C6_Rules.vue')['default']
    C7_Evaluate: typeof import('./src/components/User/CruiseInformation/C7_Evaluate.vue')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DataView: typeof import('primevue/dataview')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/User/Footer.vue')['default']
    ForgotPassword: typeof import('./src/components/User/Account_Auth/ForgotPassword.vue')['default']
    H1_SearchYachts: typeof import('./src/components/User/Home/H1_SearchYachts.vue')['default']
    H2_ListCruiseView: typeof import('./src/components/User/Home/H2_ListCruiseView.vue')['default']
    H3_Logo_Partner: typeof import('./src/components/User/Home/H3_Logo_Partner.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Login: typeof import('./src/components/User/Account_Auth/Login.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    Navbar: typeof import('./src/components/User/Navbar.vue')['default']
    OderForm: typeof import('./src/components/User/CruiseInformation/OderForm.vue')['default']
    Password: typeof import('primevue/password')['default']
    Profile: typeof import('./src/components/User/Account_Auth/Profile.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Rating: typeof import('primevue/rating')['default']
    Register: typeof import('./src/components/User/Account_Auth/Register.vue')['default']
    RoomInfo: typeof import('./src/components/User/CruiseInformation/RoomInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S1_SearchCuise: typeof import('./src/components/User/SearchCruise/S1_SearchCuise.vue')['default']
    S2_ViewListCruise: typeof import('./src/components/User/SearchCruise/S2_ViewListCruise.vue')['default']
    S21_OptionCruise: typeof import('./src/components/User/SearchCruise/S21_OptionCruise.vue')['default']
    S22_ListSearchCuise: typeof import('./src/components/User/SearchCruise/S22_ListSearchCuise.vue')['default']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    Select: typeof import('primevue/select')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    Tour: typeof import('./src/components/User/Account_Auth/Tour.vue')['default']
  }
}
